; bed.g
; called to perform automatic bed compensation via G32
;
; generated by RepRapFirmware Configuration Tool v2 on Sat May 18 2019 17:29:31 GMT+0200 (Central European Summer Time)
M561                        ; clear any bed transform
G28                         ; home

M671 X-83:-83:83 Y-83:83:0 P0.7 ; M4x40 screws on the Creality bed, thread pitch 0.7

G30 P0 X-83 Y-92 Z-99999
G30 P1 X-83 Y83 Z-99999
G30 P2 X92 Y0 Z-9999 S3

G1 X-110 Y-110 Z5 F2400 ; go to base coordinates



