; stop.g
; called when M0 (Stop) is run (e.g. when a print from SD card is cancelled)
;
; generated by RepRapFirmware Configuration Tool v3.1.4 on Sat Oct 10 2020 20:26:35 GMT+0200 (Mitteleuropäische Sommerzeit)

