; tpost0.g
; called after tool 0 has been selected
;
; generated by RepRapFirmware Configuration Tool v3.1.4 on Sat Oct 10 2020 20:26:35 GMT+0200 (Mitteleuropäische Sommerzeit)
; Wait for set temperatures to be reached
M116 P0

