; stop.g
; called when M0 (Stop) is run (e.g. when a print from SD card is cancelled)
;
; generated by RepRapFirmware Configuration Tool v2.1.8 on Fri Jan 31 2020 14:54:14 GMT+0100 (Mitteleuropäische Normalzeit)

