; tpost0.g
; called after tool 0 has been selected
;
; generated by RepRapFirmware Configuration Tool v2.1.8 on Fri Jan 31 2020 14:54:15 GMT+0100 (Mitteleuropäische Normalzeit)
; Wait for set temperatures to be reached
M116 P0

