; bed.g
; called to perform automatic bed compensation via G32
;
; generated by RepRapFirmware Configuration Tool v3.2.1-LPC+12 on Sat Jun 05 2021 16:22:58 GMT+0200 (Central European Summer Time)

M290 R0 S0   ; disable any baby stepping
M561         ; clear any bed transform
G28 Z        ; zero out Z
G29          ; probe the bed and enable compensation


