; stop.g
; called when M0 (Stop) is run (e.g. when a print from SD card is cancelled)
;
; generated by RepRapFirmware Configuration Tool v3.2.1-LPC+12 on Sat Jun 05 2021 16:22:59 GMT+0200 (Central European Summer Time)

; lift Z -- important for heater fault
G91
G0 Z10
G90

; move print bed out from under heater in case of heater fault and to present the print
G0 X90 Y90 F1200

; disable heaters

M568 P0 A0
M140 S-273.1

; disable part cooling fan

M106 P0 S0