; stop.g
; called when M0 (Stop) is run (e.g. when a print from SD card is cancelled)
;
; generated by RepRapFirmware Configuration Tool v3.2.1-LPC+12 on Sat Jun 05 2021 16:22:59 GMT+0200 (Central European Summer Time)

