; tpost0.g
; called after tool 0 has been selected
;
; generated by RepRapFirmware Configuration Tool v3.2.1-LPC+12 on Sat Jun 05 2021 16:22:59 GMT+0200 (Central European Summer Time)
; Wait for set temperatures to be reached
M116 P0

