; homey.g
; called to home the Y axis
;
; generated by RepRapFirmware Configuration Tool v2 on Sat May 18 2019 17:29:31 GMT+0200 (Central European Summer Time)
G91               ; relative positioning
G1 S1 Y-225 F1800 ; move quickly to Y axis endstop and stop there (first pass)
G1 Y5 F6000       ; go back a few mm
G1 S1 Y-225 F360  ; move slowly to Y axis endstop once more (second pass)
G90               ; absolute positioning
G0 Y0 F2400       ; move to a safe location
